/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import com.mycompany.buscador_empleov1.Empresa;
import com.mycompany.buscador_empleov1.Formulario_Company;
import datos.FirestoreData;
import javax.swing.JOptionPane;

/**
 *
 * @author Edison
 */
public class Formulario_Empresa extends javax.swing.JFrame {

    /**
     * Creates new form Formulario_Empresa
     */
    public Formulario_Empresa() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Formulario Empresa");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txaCompannyDescription = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        txaCompanyH = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        txaCompanyR = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        txaCompanyP = new javax.swing.JTextArea();
        lblEname = new javax.swing.JLabel();
        txtCompanyPhoneNumber = new javax.swing.JTextField();
        lblEaddress = new javax.swing.JLabel();
        lblIdEmpresa = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaEAddress = new javax.swing.JTextArea();
        btnGetUserData = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        lblCompanyNumber = new javax.swing.JLabel();
        txtCompanyEmail = new javax.swing.JTextField();
        lblCEmanil = new javax.swing.JLabel();
        txtEmpresaID = new javax.swing.JTextField();
        txtEmpresaName = new javax.swing.JTextField();
        lblTituloE = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setText("Requirimentos basicos parte de la Empresa");

        jLabel13.setText("Puestos Disponibles");

        txaCompannyDescription.setColumns(20);
        txaCompannyDescription.setRows(5);
        jScrollPane2.setViewportView(txaCompannyDescription);

        txaCompanyH.setColumns(20);
        txaCompanyH.setRows(5);
        jScrollPane3.setViewportView(txaCompanyH);

        txaCompanyR.setColumns(20);
        txaCompanyR.setRows(5);
        jScrollPane4.setViewportView(txaCompanyR);

        txaCompanyP.setColumns(20);
        txaCompanyP.setRows(5);
        jScrollPane5.setViewportView(txaCompanyP);

        lblEname.setText("Nombre");

        lblEaddress.setText("Ubicacion exacta de la Empresa");

        lblIdEmpresa.setText("Numero de Identificacion");

        txaEAddress.setColumns(20);
        txaEAddress.setRows(5);
        jScrollPane1.setViewportView(txaEAddress);

        btnGetUserData.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnGetUserData.setText("Guardar Datos");
        btnGetUserData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetUserDataActionPerformed(evt);
            }
        });

        jLabel8.setText("Informacion de Interes");

        lblCompanyNumber.setText("Numero de Telefono o Celular");

        lblCEmanil.setText("Email");

        lblTituloE.setText("Informacion de la Empresa");

        jLabel10.setText("Descripción General de la Empresa");

        jLabel11.setText("Horarios de atencion");

        jButton1.setText("Regresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblTituloE)
                    .addComponent(lblEname)
                    .addComponent(lblIdEmpresa)
                    .addComponent(lblEaddress)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblCompanyNumber)
                    .addComponent(lblCEmanil)
                    .addComponent(txtEmpresaID)
                    .addComponent(txtEmpresaName)
                    .addComponent(txtCompanyEmail)
                    .addComponent(txtCompanyPhoneNumber))
                .addGap(100, 100, 100)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTitulo)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnGetUserData, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTituloE)
                        .addGap(18, 18, 18)
                        .addComponent(lblIdEmpresa))
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEmpresaID, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblEname)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEmpresaName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(240, 240, 240)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCompanyNumber)
                    .addComponent(lblTitulo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtCompanyPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblCEmanil)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCompanyEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 11, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblEaddress)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(btnGetUserData, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGetUserDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetUserDataActionPerformed
        // TODO add your handling code here:
        
        /*Formulario_Company Fc = new Formulario_Company();*/
        P_Empresa P = new P_Empresa();
        FirestoreData fd = new FirestoreData();
        
        Empresa E = new Empresa();
        E.setID(txtEmpresaID.getText());
        E.setName(txtEmpresaName.getText());
        E.setAddress(txaEAddress.getText());
        E.setPhoneNumber(txtCompanyPhoneNumber.getText());
        E.setEmail(txtCompanyEmail.getText());       
        E.setCompanyDescription(txaCompannyDescription.getText());
        E.setHorarios(txaCompanyH.getText());
        E.setRequerimientos(txaCompanyR.getText());
        E.setPuesto(txaCompanyP.getText());
        
        fd.guardarEmpresa(E);
        JOptionPane.showMessageDialog(this, "Datos Guardados");
        P.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_btnGetUserDataActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        P_Empresa i = new P_Empresa();
        i.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulario_Empresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulario_Empresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulario_Empresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulario_Empresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formulario_Empresa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGetUserData;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel lblCEmanil;
    private javax.swing.JLabel lblCompanyNumber;
    private javax.swing.JLabel lblEaddress;
    private javax.swing.JLabel lblEname;
    private javax.swing.JLabel lblIdEmpresa;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTituloE;
    private javax.swing.JTextArea txaCompannyDescription;
    private javax.swing.JTextArea txaCompanyH;
    private javax.swing.JTextArea txaCompanyP;
    private javax.swing.JTextArea txaCompanyR;
    private javax.swing.JTextArea txaEAddress;
    private javax.swing.JTextField txtCompanyEmail;
    private javax.swing.JTextField txtCompanyPhoneNumber;
    private javax.swing.JTextField txtEmpresaID;
    private javax.swing.JTextField txtEmpresaName;
    // End of variables declaration//GEN-END:variables
}
